### ISSUE TITLE
Critical dependency error

### ISSUE THREAD

**Issue by yarnball** [shinnn/fetch-cheerio-object#6]
Thanks for this great library.

I keep getting a `Critical dependency error`. As per below. 

What needs to be done to fix this?

Thanks

```
./~/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
```

**Comment by shinnn** [comment]
Nothing to do with this project,

**Comment by yarnball** [comment]
Then it must have an issue with `Create-react-app`. I have installed to a new project which was created using `Create-react-app`.

**Comment by shinnn** [comment]
@yarnball Can you provide me an evidence that this repository includes `iconv-loader.js`? if you can't, as i said, `Critical dependency` error has nothing to do with this project.

**Comment by yarnball** [comment]
Sure, I've just created a repo with the sample [here](https://github.com/yarnball/ReactURLSraper)

**Comment by shinnn** [comment]
Eh, why did you think the sample repository work for this issue? I value my time so I'll never check your repo.

My question is even more simple: Can you find `encoding/lib/iconv-loader.js` in this list? Or my browser or Github website hide it wrongly?

![image](https://user-images.githubusercontent.com/1131567/27783890-024f675e-6013-11e7-8be8-05d8692a943c.png)

**Comment by yarnball** [comment]
You've used `node-fetch` which could be the cause. Apparently`whatwg-fetch` fixes this

**Comment by shinnn** [comment]
> `node-fetch` which could be the cause

No, it's not even `node-fetch`'s fault. I really agree with this comment: https://github.com/bitinn/node-fetch/issues/41#issuecomment-137837210

I am saying the same thing again and again, this is not a fetch-cheerio-object issue and should have not be posted here.
